package com.travelcompanion.service;

import com.travelcompanion.dto.CompanionAlertDto;
import com.travelcompanion.dto.ItineraryItemDto;
import com.travelcompanion.entity.CompanionAlert;
import com.travelcompanion.entity.ItineraryItem;
import com.travelcompanion.entity.Trip;
import com.travelcompanion.repository.CompanionAlertRepository;
import com.travelcompanion.repository.ItineraryItemRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class CompanionAlertService {

    private final CompanionAlertRepository alertRepository;
    private final ItineraryItemRepository itineraryItemRepository;
    private final TripService tripService;
    private final AIService aiService;

    public List<CompanionAlertDto> getTripAlerts(Long tripId) {
        Trip trip = tripService.getTripEntity(tripId);
        List<CompanionAlert> alerts = alertRepository.findByTripIdOrderByCreatedAtDesc(tripId);
        if (alerts.isEmpty()) {
            List<ItineraryItem> items = itineraryItemRepository.findByTripIdOrderByDayNumberAscStartTimeAsc(tripId);
            List<ItineraryItemDto> dtoList = items.stream().map(i -> ItineraryItemDto.builder()
                    .dayNumber(i.getDayNumber())
                    .startTime(i.getStartTime())
                    .endTime(i.getEndTime())
                    .placeName(i.getPlaceName())
                    .category(i.getCategory())
                    .estimatedCost(i.getEstimatedCost())
                    .build()).collect(Collectors.toList());

            alerts = aiService.generateLiveCompanionAlerts(trip, dtoList);
            alerts = alertRepository.saveAll(alerts);
        }
        return alerts.stream().map(this::toDto).collect(Collectors.toList());
    }

    @Transactional
    public CompanionAlertDto acceptAlert(Long alertId) {
        CompanionAlert alert = alertRepository.findById(alertId)
                .orElseThrow(() -> new RuntimeException("Alert not found: " + alertId));
        alert.setStatus("ACCEPTED");

        // If replacement item exists, adjust the itinerary
        if (alert.getOriginalItem() != null && alert.getReplacementItem() != null) {
            List<ItineraryItem> items = itineraryItemRepository.findByTripIdOrderByDayNumberAscStartTimeAsc(alert.getTrip().getId());
            for (ItineraryItem item : items) {
                if (item.getPlaceName().toLowerCase().contains(alert.getOriginalItem().toLowerCase()) ||
                    alert.getOriginalItem().toLowerCase().contains(item.getPlaceName().toLowerCase())) {
                    item.setPlaceName(alert.getReplacementItem());
                    item.setRecommendationReason("Updated by AI Companion: " + alert.getSuggestedAction());
                    itineraryItemRepository.save(item);
                    break;
                }
            }
        }
        return toDto(alertRepository.save(alert));
    }

    @Transactional
    public CompanionAlertDto rejectAlert(Long alertId) {
        CompanionAlert alert = alertRepository.findById(alertId)
                .orElseThrow(() -> new RuntimeException("Alert not found: " + alertId));
        alert.setStatus("REJECTED");
        return toDto(alertRepository.save(alert));
    }

    public String askWhy(Long alertId) {
        CompanionAlert alert = alertRepository.findById(alertId)
                .orElseThrow(() -> new RuntimeException("Alert not found: " + alertId));
        return alert.getReasonWhy() != null ? alert.getReasonWhy() :
                "This recommendation was generated by comparing real-time meteorological conditions, historical visitor crowd volumes, and transit delays against your selected trip mood.";
    }

    private CompanionAlertDto toDto(CompanionAlert alert) {
        return CompanionAlertDto.builder()
                .id(alert.getId())
                .tripId(alert.getTrip().getId())
                .alertType(alert.getAlertType())
                .title(alert.getTitle())
                .message(alert.getMessage())
                .suggestedAction(alert.getSuggestedAction())
                .originalItem(alert.getOriginalItem())
                .replacementItem(alert.getReplacementItem())
                .reasonWhy(alert.getReasonWhy())
                .status(alert.getStatus())
                .createdAt(alert.getCreatedAt())
                .build();
    }
}
